import PDFDocument from "pdfkit";

import { formatCurrency, formatDate } from "@/lib/format";
import type { InvoiceRecord } from "@/lib/domain/models";

function streamToBuffer(document: PDFKit.PDFDocument) {
  return new Promise<Buffer>((resolve, reject) => {
    const chunks: Buffer[] = [];

    document.on("data", (chunk) => chunks.push(Buffer.from(chunk)));
    document.on("end", () => resolve(Buffer.concat(chunks)));
    document.on("error", (error) => reject(error));
    document.end();
  });
}

export async function renderInvoicePdf(options: {
  invoice: InvoiceRecord;
  customerName: string;
  lineItems: Array<{
    description: string;
    amount: number;
  }>;
}) {
  const document = new PDFDocument({
    margin: 48,
    size: "LETTER",
  });

  document.fontSize(24).fillColor("#16232b").text("Metro Trailer");
  document
    .fontSize(11)
    .fillColor("#5d6870")
    .text("Rental operations invoice", { paragraphGap: 18 });

  document
    .fontSize(12)
    .fillColor("#16232b")
    .text(`Invoice: ${options.invoice.invoiceNumber}`)
    .text(`Customer: ${options.customerName}`)
    .text(`Contract: ${options.invoice.contractNumber}`)
    .text(`Invoice date: ${formatDate(options.invoice.invoiceDate)}`)
    .text(`Due date: ${formatDate(options.invoice.dueDate)}`)
    .moveDown();

  document.fontSize(13).fillColor("#16232b").text("Line items", {
    underline: true,
  });
  document.moveDown(0.5);

  options.lineItems.forEach((lineItem) => {
    document
      .fontSize(11)
      .fillColor("#16232b")
      .text(lineItem.description, { continued: true })
      .text(formatCurrency(lineItem.amount), {
        align: "right",
      });
  });

  document.moveDown();
  document
    .fontSize(12)
    .fillColor("#16232b")
    .text(`Balance due: ${formatCurrency(options.invoice.balanceAmount)}`, {
      align: "right",
    })
    .moveDown();

  document
    .fontSize(10)
    .fillColor("#5d6870")
    .text(
      "This PDF was generated by Metro Trailer for operational billing review. Posted accounting and payment execution may sync through QuickBooks Online and Stripe.",
      {
        lineGap: 4,
      },
    );

  return streamToBuffer(document);
}
